# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Seed Users
User.create(
  [
    {
      patient_key: "4286-5",
      patient_mrn: "4286",
      episode_number: "5",
      first_admission_date: "2017-07-04",
      first_name: "ALISON",
      last_name: "KLINE",
      email: "alison.kline25@gmail.com",
      phone: "215-983-5545",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "13717-5",
      patient_mrn: "13717",
      episode_number: "5",
      first_admission_date: "2019-03-05",
      first_name: "SARA",
      last_name: "SWINNICH",
      email: "sara.swinnich@gmail.com",
      phone: "717-443-8791",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "46006-4",
      patient_mrn: "46006",
      episode_number: "4",
      first_admission_date: "2020-05-01",
      first_name: "THOMAS",
      last_name: "BROWN",
      email: "tbrownfl3414@gmail.com",
      phone: "607-725-8038",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "48697-2",
      patient_mrn: "48697",
      episode_number: "2",
      first_admission_date: "2020-06-16",
      first_name: "DAWN",
      last_name: "WILLIAMS",
      email: "dawnm0569@aim.com",
      phone: "267-733-4206",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "50023-3",
      patient_mrn: "50023",
      episode_number: "3",
      first_admission_date: "2020-07-25",
      first_name: "RICHARD",
      last_name: "RAMBO",
      email: "psu4158@gmail.com",
      phone: "215-264-1829",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "51170-2",
      patient_mrn: "51170",
      episode_number: "2",
      first_admission_date: "2020-09-01",
      first_name: "KIMBERLY",
      last_name: "OZER",
      email: "kmejozer@yahoo.com",
      phone: "412-287-1295",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "51179-3",
      patient_mrn: "51179",
      episode_number: "3",
      first_admission_date: "2020-09-01",
      first_name: "KAYLA",
      last_name: "ASH",
      email: "kaylaash09@gmail.com",
      phone: "215-881-3285",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "51355-2",
      patient_mrn: "51355",
      episode_number: "2",
      first_admission_date: "2020-09-04",
      first_name: "KAREN",
      last_name: "PHILLIPS",
      email: "klphillips65@gmail.com",
      phone: "610-636-3461",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "53682-2",
      patient_mrn: "53682",
      episode_number: "2",
      first_admission_date: "2020-11-10",
      first_name: "ANN",
      last_name: "ASHTON",
      email: "ashtonann3@gmail.com",
      phone: "610-715-8756",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "53907-3",
      patient_mrn: "53907",
      episode_number: "3",
      first_admission_date: "2020-11-18",
      first_name: "MELISSA",
      last_name: "PURVIS",
      email: "melissapurvis@verizon.net",
      phone: "484-356-4755",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "54204-3",
      patient_mrn: "54204",
      episode_number: "3",
      first_admission_date: "2020-11-30",
      first_name: "CHRISTOPHER",
      last_name: "CALVO",
      email: "wayc0s113@gmail.com",
      phone: "484-644-0104",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "54524-2",
      patient_mrn: "54524",
      episode_number: "2",
      first_admission_date: "2020-12-02",
      first_name: "KRISTEN",
      last_name: "MOYER",
      email: "kmoyer0104@gmail.com",
      phone: "610-549-3647",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "56465-2",
      patient_mrn: "56465",
      episode_number: "2",
      first_admission_date: "2021-01-27",
      first_name: "ALLISON",
      last_name: "RAMSBOTTOM",
      email: "alliramsbottom@gmail.com",
      phone: "617-872-8324",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "57150-2",
      patient_mrn: "57150",
      episode_number: "2",
      first_admission_date: "2021-02-12",
      first_name: "MICHELLE",
      last_name: "SPRUCEBANK",
      email: "ellespruce@yahoo.com",
      phone: "717-379-2339",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "56813-1",
      patient_mrn: "56813",
      episode_number: "1",
      first_admission_date: "2021-02-08",
      first_name: "ADRIANNE",
      last_name: "LYNCH",
      email: "adri242662@gmail.com",
      phone: "610-357-8539",
      password: "password123",
      password_confirmation: "password123",
    },{
      patient_key: "51355-2",
      patient_mrn: "51355",
      episode_number: "2",
      first_admission_date: "2020-09-04",
      first_name: "KAREN",
      last_name: "PHILLIPS",
      email: "klphillips65@gmail.com",
      phone: "610-636-3461",
      password: "password123",
      password_confirmation: "password123",
    }
  ]
)

# Seed Appointments
Appointment.create(
  [
    {
      "user_id": User.find_by(patient_key: "4286-5").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580551"
    },{
      "user_id": User.find_by(patient_key: "13717-5").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580552"
    },{
      "user_id": User.find_by(patient_key: "46006-4").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580553"
    },{
      "user_id": User.find_by(patient_key: "48697-2").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580554"
    },{
      "user_id": User.find_by(patient_key: "50023-3").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580555"
    },{
      "user_id": User.find_by(patient_key: "51170-2").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580556"
    },{
      "user_id": User.find_by(patient_key: "51179-3").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580557"
    },{
      "user_id": User.find_by(patient_key: "51355-2").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580558"
    },{
      "user_id": User.find_by(patient_key: "53682-2").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580559"
    },{
      "user_id": User.find_by(patient_key: "53907-3").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580560"
    },{
      "user_id": User.find_by(patient_key: "54204-3").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580561"
    },{
      "user_id": User.find_by(patient_key: "54524-2").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580562"
    },{
      "user_id": User.find_by(patient_key: "56465-2").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580563"
    },{
      "user_id": User.find_by(patient_key: "57150-2").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580564"
    },{
      "user_id": User.find_by(patient_key: "56813-1").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Group",
      "date": "2021-02-24",
      "start_time": "10:00 AM",
      "end_time": "01:00 PM",
      "description": "TH-IOP",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "580565"
    },{
      "user_id": User.find_by(patient_key: "51355-2").id,
      "site_name": "Devon SUD Outpatient",
      "session_type": "Individual",
      "date": "2021-02-24",
      "start_time": "09:15 AM",
      "end_time": "09:45 AM",
      "description": "TH-Non-Billable Individual Service",
      "facilitator_first_name": "MELISSA",
      "facilitator_last_name": "CARR",
      "facilitator_email": "MCARR@recoverycoa.com",
      "primary_therapist_first_name": "Melissa",
      "primary_therapist_last_name": "Carr",
      "primary_therapist_email": "MCARR@recoverycoa.com",
      "id": "638703"
    }
  ]
)
